### ISSUE TITLE
Firefox Android fails to sync with TokenServerMalformedResponseException

### ISSUE THREAD

**Issue by licryle** [YunoHost-Apps/ffsync_ynh#7]
Hi folks,

I've been running ffsync for while, but I haven't dug yet this issue in depth: the sync server doesn't seem to respond properly for Android clients. Full adb log:

```
12-24 16:08:32.576 27846 29202 I FxAccounts: firefox :: AndroidFxAccount :: Moving account named like [removed] to state Cohabiting
12-24 16:08:32.603 27846 29202 W FxAccounts: firefox :: FxAccountSyncAdapter :: Global session failed.
12-24 16:08:32.603 27846 29202 E FxAccounts: firefox :: FxAccountSyncAdapter :: Got exception syncing.
12-24 16:08:32.603 27846 29202 E FxAccounts: org.mozilla.gecko.tokenserver.TokenServerException$TokenServerMalformedResponseException: **org.mozilla.gecko.sync.UnexpectedJSONException$BadRequiredFieldJSONException: Expected key not present in result: hashed_fxa_uid**
12-24 16:08:32.603 27846 29202 E FxAccounts: 	at org.mozilla.gecko.tokenserver.TokenServerClient.processResponse(TokenServerClient.java:226)
12-24 16:08:32.603 27846 29202 E FxAccounts: 	at org.mozilla.gecko.tokenserver.TokenServerClient$TokenFetchResourceDelegate.handleHttpResponse(TokenServerClient.java:281)
12-24 16:08:32.603 27846 29202 E FxAccounts: 	at org.mozilla.gecko.sync.net.BaseResource.execute(BaseResource.java:342)
12-24 16:08:32.603 27846 29202 E FxAccounts: 	at org.mozilla.gecko.sync.net.BaseResource.go(BaseResource.java:373)
12-24 16:08:32.603 27846 29202 E FxAccounts: 	at org.mozilla.gecko.sync.net.BaseResource.get(BaseResource.java:379)
12-24 16:08:32.603 27846 29202 E FxAccounts: 	at org.mozilla.gecko.tokenserver.TokenServerClient.getTokenFromBrowserIDAssertion(TokenServerClient.java:329)
12-24 16:08:32.603 27846 29202 E FxAccounts: 	at org.mozilla.gecko.fxa.sync.FxAccountSyncAdapter.syncWithAssertion(FxAccountSyncAdapter.java:463)
12-24 16:08:32.603 27846 29202 E FxAccounts: 	at org.mozilla.gecko.fxa.sync.FxAccountSyncAdapter$3.handleMarried(FxAccountSyncAdapter.java:667)
12-24 16:08:32.603 27846 29202 E FxAccounts: 	at org.mozilla.gecko.fxa.authenticator.FxADefaultLoginStateMachineDelegate.handleFinal(FxADefaultLoginStateMachineDelegate.java:81)
12-24 16:08:32.603 27846 29202 E FxAccounts: 	at org.mozilla.gecko.fxa.login.FxAccountLoginStateMachine$ExecuteDelegate.handleTransition(FxAccountLoginStateMachine.java:64)
12-24 16:08:32.603 27846 29202 E FxAccounts: 	at org.mozilla.gecko.fxa.login.Cohabiting$1.handleSuccess(Cohabiting.java:46)
12-24 16:08:32.603 27846 29202 E FxAccounts: 	at org.mozilla.gecko.fxa.login.Cohabiting$1.handleSuccess(Cohabiting.java:28)
12-24 16:08:32.603 27846 29202 E FxAccounts: 	at org.mozilla.gecko.background.fxa.FxAccountClient20$5.handleSuccess(FxAccountClient20.java:579)
12-24 16:08:32.603 27846 29202 E FxAccounts: 	at org.mozilla.gecko.background.fxa.FxAccountClient20$ResourceDelegate$2.run(FxAccountClient20.java:279)
12-24 16:08:32.603 27846 29202 E FxAccounts: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
12-24 16:08:32.603 27846 29202 E FxAccounts: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
12-24 16:08:32.603 27846 29202 E FxAccounts: 	at java.lang.Thread.run(Thread.java:764)
12-24 16:08:32.603 27846 29202 E FxAccounts: Caused by: **org.mozilla.gecko.sync.UnexpectedJSONException$BadRequiredFieldJSONException: Expected key not present in result: hashed_fxa_uid**
12-24 16:08:32.603 27846 29202 E FxAccounts: 	at org.mozilla.gecko.sync.ExtendedJSONObject.throwIfFieldsMissingOrMisTyped(ExtendedJSONObject.java:397)
12-24 16:08:32.603 27846 29202 E FxAccounts: 	at org.mozilla.gecko.tokenserver.TokenServerClient.processResponse(TokenServerClient.java:223)
12-24 16:08:32.603 27846 29202 E FxAccounts: 	... 16 more
12-24 16:08:32.604 27846 29175 I FxAccounts: firefox :: FxAccountSyncAdapter :: Syncing done.
12-24 16:08:32.608 27846 27846 I FxAccounts: firefox :: FxAccountStatusFragment :: Got sync finished message; refreshing.
12-24 16:08:32.610 27846 27846 I FxAccounts: firefox :: FxAccountStatusFragment :: AvatarURI is empty, skipping profile image fetch.
12-24 16:08:34.638 27846 27846 I FxAccounts: firefox :: FxAccountStatusFragment :: Profile avatar cache update action broadcast received.
12-24 16:08:34.640 27846 27846 I FxAccounts: firefox :: FxAccountStatusFragment :: AvatarURI is empty, skipping profile image fetch.
12-24 16:09:23.745 27846 29466 I FxAccounts: firefox :: FxAccountSyncAdapter :: Syncing FxAccount account named like [removed] for authority org.mozilla.firefox.db.browser with instance org.mozilla.gecko.fxa.sync.FxAccountSyncAdapter@91f6557.
12-24 16:09:23.750 27846 29466 I FxAccounts: firefox :: FxAccountSyncAdapter :: Account last synced at: -1
12-24 16:09:23.750 27846 29466 I FxAccounts: firefox :: FirefoxAccounts :: Sync options -- scheduling now: false
12-24 16:09:23.756 27846 29466 I FxAccounts: firefox :: FxAccountSyncAdapter :: Not syncing (background): must wait another 3544589ms.
```

**Comment by licryle** [comment]
Just tried to naively replace with latest mozilla versions of their servers:

/opt/yunohost/ffsync/local/lib/python2.7/site-packages/syncstorage by https://github.com/mozilla-services/server-syncstorage/tree/v1.6.12/syncstorage

And

/opt/yunohost/ffsync/local/lib/python2.7/site-packages/tokenserver by https://github.com/mozilla-services/tokenserver/tree/1.2.27/tokenserver
+ (removing the 'first_seen_at' tracking in views.py)

And it surprinsingly fixed the issue and works well :)

I suggest changing the requirements.txt to point to the latest versions available, or at least newer ones.

There may be downstream compatibility issues when requirements.txt is updated - I'm actually pretty surprised nothing broke considering they introduced new library dependencies.

**Comment by Jibec** [comment]
Have you tried this? https://github.com/YunoHost-Apps/ffsync_ynh/pull/6
-- 
Jean-Baptiste Holcroft

**Comment by Josue-T** [comment]
Now I have tried #6 and it fixed this issue on my side.

**Comment by Josue-T** [comment]
I close this issue as I think that it's solved.

Don't hesitate to reopen if you encounter this issue.
